### ISSUE TITLE
Adding bounds

### ISSUE THREAD

**Issue by bluss** [mcarton/rust-derivative#1]
Neat project. Here's an idea of something that I needed for a project: A way to use derive(Debug) but control which trait bounds are used on the typarms.

Example:

```rust
struct EdgeIndex<Ix>(Ix);
// has custom impl
impl<Ix: IndexType> fmt::Debug for EdgeIndex<Ix> { ... }·
```

unfortunately the bound from the custom impl becomes viral, so I can't do this:

```rust
#[derive(Debug)]
struct Node<Ix> {
next: [EdgeIndex<Ix>; 2]
}
```

The idea would be something like: `#[derivable(bounds(Ix: IndexType))]` if that's even possible, to customize which bounds are used for `Node`'s Debug implementation.

Detailed bound control is also useful the same way in Clone in particular, but I guess in most derives.

Another idea, just to tack it on, is a variant of derive clone that also implements `Clone::clone_from`.

**Comment by mcarton** [comment]
Thanks!
I did add a [way to override inferred bounds](https://mcarton.github.io/rust-derivative/Debug.html#custom-bound) already.

You example would be something like that:
```rust
#[derive(Derivative)]
#[derivative(Debug)]
struct Node<Ix> {
    #[derivarive(Debug(bound="Ix: IndexType"))]
    next: [EdgeIndex<Ix>; 2]
}
```

**Comment by bluss** [comment]
Great! (I tried to approach this with parse-macros, but it does not yet support type parameter defaults.)

**Comment by mcarton** [comment]
Closing as bounds are supported and I have opened another issue for `Clone::clone_from`.
Feel free to open other issues if you have any more idea!
