### ISSUE TITLE
Update `syn` and `quote` to latest versions

### ISSUE THREAD

**Issue by azriel91** [mcarton/rust-derivative#25]
One of my projects compiles multiple versions of `syn` and `quote` due to different crate dependencies using different versions of these crates. To reduce the number of crates I have to build, I'm going around bumping the `syn` and `quote` versions to `0.15` and `0.6` (current latest of each).

Hopefully you don't mind taking a PR for this: #26

**Comment by mcarton** [comment]
Fixed in #26.
