### ISSUE TITLE
Improved `Partial{Eq,Ord}` derive

### ISSUE THREAD

**Issue by mcarton** [mcarton/rust-derivative#3]
Provide `derivative({PartialEq, Eq, PartialOrd, Ord})` with:
- `Eq`:
  - [x] custom `bound`
- `PartialEq`:
  - [x] custom `bound`
  - [x] `ignore` on a field
  - [x] `compare_with` on a field
- `Ord`:
  - [x] custom `bound`
  - [x] `ignore` on a field
  - [x] `compare_with` on a field
- `PartialOrd`:
  - [x] custom `bound`
  - [x] `ignore` on a field
  - [x] `compare_with` on a field

`enum` are tricky¹ as there is no stable way to compare discriminants yet. See https://github.com/rust-lang/rfcs/pull/1696.

---

1: not for `Eq`.

**Comment by mcarton** [comment]
`Eq` is done. I'm going to wait a while on https://github.com/dtolnay/syn/issues/27 for the others.

**Comment by elidupree** [comment]
What's the current status of this? I have a project where it would be significantly helpful if I could derive Ord with custom bounds (to work around https://github.com/rust-lang/rust/issues/26925 ). I'd submit a PR, but unfortunately the proc-macro code is still fairly opaque to me and I don't want to do it *wrong*.
