### ISSUE TITLE
Please update to syn/quote/proc-macro2 version 1.0

### ISSUE THREAD

**Issue by Lokathor** [mcarton/rust-derivative#43]
As the title says

**Comment by mcarton** [comment]
Syn supports rustc 1.31 and up while derivative supports rustc 1.15 or later. This would require a version bump, but it seems like a good idea anyway.

**Comment by malobre** [comment]
Any rough ETA on this ? We're trying to remove duplicate dependencies in https://github.com/amethyst/rendy/issues/203 and derivative is the last crate using an old syn version.
I know you [mentioned](https://github.com/mcarton/rust-derivative/pull/50#issuecomment-527255272) wanting to makes other changes before bumping to 2.0, I'm available if you need help.

**Comment by jaynus** [comment]
Ping on this issue and #59 

Has this stalled? Is this crate dead? This is beginning to be painful to compile times needing to compile an ancient version of syn.

**Comment by Dushistov** [comment]
Looks like create is not maintained any more. Time to fork?

**Comment by mcarton** [comment]
Done!
