### ISSUE TITLE
Skip enum fields for `Debug` implementation

### ISSUE THREAD

**Issue by GeorgeHahn** [mcarton/rust-derivative#76]
One common pattern in rust is to represent commands with enums. Multiple related commands map to different enum members and their parameters map to fields. Associated input/output buffers or other data structures may be included as enum fields. These often require a custom `Debug` implementation to display the control parameters but omit large buffers or non-debug data structures. This would be a nice pattern to support.

#### Enums with named fields
```rust
enum Command {
    #[derivative(Debug(skip("buffer"))]
    Rebuild { target: IsDebug, buffer: NotDebug },
}
```

#### Enums with unnamed fields
```rust
// Explicit by field
enum Command {
    Rebuild(IsDebug, #[derivative(Debug="skip")] NotDebug),
}

// Explicit by type
enum Command {
    #[derivative(Debug(skip(NotDebug)))]
    Rebuild(IsDebug, NotDebug),
}

// Implicit
enum Command {
    #[derivative(Debug="skip_non_debug")]
    Rebuild(IsDebug, NotDebug),
}
```

#### Generated code

```rust
impl Debug for Command {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Command::Rebuild(val, _) => f.debug_tuple("Rebuild").field(&val).finish(),
        }
    }
}
```

**Comment by mcarton** [comment]
This is [already possible](https://mcarton.github.io/rust-derivative/Debug.html#ignoring-a-field), eg.:

```rust
use derivative; // 2.1.1

#[derive(derivative::Derivative)]
#[derivative(Debug)]
enum Command {
    Rebuild {
        target: String,
        #[derivative(Debug = "ignore")] // ← this is what you want
        buffer: NotDebug,
    },
}

struct NotDebug;

fn main() {
    println!(
        "{:?}",
        Command::Rebuild {
            target: "foo".to_string(),
            buffer: NotDebug
        }
    );
}
```

[Permalink to the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=67d8de32195c21a1ac33297800eb56b5)
