### ISSUE TITLE
Invalid attribute error when combined with thiserror

### ISSUE THREAD

**Issue by attente** [mcarton/rust-derivative#78]
**Describe the bug**
Combining the derive macros `derivative::Derivative` and `thiserror::Error` seems to break arbitrary debug expressions in thiserror.

**To Reproduce**
```rust
use {derivative::Derivative, std::fmt::Debug, thiserror::Error as ThisError};

trait NonDebugTrait {
    type DebugAssociatedType: Debug;
}

#[derive(ThisError, Derivative)]
#[derivative(Debug(bound = "T: NonDebugTrait"))]
enum ThatError<T: NonDebugTrait> {
    #[error("error {:?}", .0)]
    Variant(T::DebugAssociatedType),
}

fn main() {
    println!("Hello, world!");
}
```

**Expected behavior**
Successful compilation.

**Errors**
```
error: invalid attribute: expected identifier or literal
  --> src/main.rs:10:27
   |
10 |     #[error("error {:?}", .0)]
   |                           ^
```

**Version (please complete the following information):**
```sh
rustup --version # n/a
cargo --version # cargo 1.49.0-nightly (2af662e22 2020-11-12)
rustc --version # rustc 1.50.0-nightly (603ab5bd6 2020-11-15)
```
 - Version of `derivative`: 2.1.1

**Additional context**
I originally reported this at https://github.com/dtolnay/thiserror/issues/111, but @dtolnay indicated this was a problem with rust-derivative, not thiserror.

**Comment by mcarton** [comment]
Fixed in #79 and released as v2.1.2 just now.
